version: '3.9'  

services:
  hugin:
    image: klakegg/hugo:0.107.0-ext-alpine
    volumes:
      - ".:/src"
    ports:
      - "1313:1313"
    command: server -D
    networks:
      - valhalla

networks:
  valhalla:
    driver: bridge