version: '3.9'  

services:
  hugin:
    image: klakegg/hugo:0.107.0-ext-alpine
    volumes:
      - ".:/src"
    ports:
      - "1313:1313"
    command: server -D --baseURL 172.105.247.82
    networks:
      - valhalla

networks:
  valhalla:
    driver: bridge