version: '3.3'  

services:
  hugin:
    image: klakegg/hugo:0.107.0-ext-alpine
    volumes:
      - ".:/src"
    ports:
      - "1313:1313"
    command: server -D --baseURL 127.0.0.1
    networks:
      - valhalla

networks:
  valhalla:
    driver: bridge
